import type { Metadata } from "next";
import { Barlow, Modern_Antiqua, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import CustomToast from "@/components/miscellaneousUIcomponents/CustomToast";

const barlow = Barlow({
  weight: "700",
  subsets: ["latin"],
});

const modernFont = Modern_Antiqua({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children} : {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black h-screen w-screen overflow-hidden`}
      >
        <Providers>
          {children}
          <CustomToast/>
        </Providers>
      </body>
    </html>
  );
}
