export function GET() {
    return Response.json({
  "login": "kharsh560",
  "id": 122051425,
  "node_id": "U_kgDOB0ZbYQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/122051425?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kharsh560",
  "html_url": "https://github.com/kharsh560",
  "followers_url": "https://api.github.com/users/kharsh560/followers",
  "following_url": "https://api.github.com/users/kharsh560/following{/other_user}",
  "gists_url": "https://api.github.com/users/kharsh560/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kharsh560/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kharsh560/subscriptions",
  "organizations_url": "https://api.github.com/users/kharsh560/orgs",
  "repos_url": "https://api.github.com/users/kharsh560/repos",
  "events_url": "https://api.github.com/users/kharsh560/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kharsh560/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Kumar Harsh",
  "company": null,
  "blog": "https://kharsh560.github.io/kh_aboutme.github.io/",
  "location": "Delhi, India",
  "email": null,
  "hireable": null,
  "bio": "Learning to solving real-life problems through codes!\r\nUndergrad at MAIT, Delhi, pursuing my B.Tech degree in AI&ML.",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 8,
  "following": 11,
  "created_at": "2023-01-05T19:19:49Z",
  "updated_at": "2025-03-08T15:20:20Z"
})
}

